package com.mhsx.actorsticker;

import android.app.*;
import android.content.*;
import android.database.Cursor;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.media.MediaMetadataRetriever;
import android.net.Uri;
import android.os.*;
import android.provider.OpenableColumns;
import android.view.*;
import android.widget.*;

import androidx.media3.common.util.UnstableApi;

import java.io.File;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.util.*;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

/**
 * v0.8 Full Studio layer: learned offline face identity, actor repair tools,
 * multi-actor scene composition, persistent foreground render queue, real frame
 * before/after preview, project history, storage/tuning and smart suggestions.
 */
@UnstableApi
public class MainActivityV080 extends MainActivityV070 {
    private static final String TAB="v080_studio_tab";
    private final Handler ui80=new Handler(Looper.getMainLooper());
    private final ExecutorService worker80=Executors.newSingleThreadExecutor();
    private boolean dead80;
    private V080StudioStore studio;
    private V080ExportQueue queue;

    private final Runnable loop80=new Runnable(){@Override public void run(){if(dead80)return;try{fixVersion(getWindow().getDecorView());injectStudioTab(getWindow().getDecorView());refreshExportProgress();}catch(Throwable ignored){}ui80.postDelayed(this,550);}};

    @Override public void onCreate(Bundle state){super.onCreate(state);studio=new V080StudioStore(this);queue=new V080ExportQueue(this);queue.resetInterrupted();ensureDefaults80();ui80.post(loop80);worker80.execute(this::touchCurrentProject);}
    @Override protected void onDestroy(){dead80=true;ui80.removeCallbacksAndMessages(null);worker80.shutdownNow();super.onDestroy();}

    private SharedPreferences p(){return getSharedPreferences("actor_sticker",MODE_PRIVATE);}
    private int dp(int x){return Math.round(x*getResources().getDisplayMetrics().density);}
    private void ensureDefaults80(){SharedPreferences x=p();SharedPreferences.Editor e=x.edit();if(!x.contains("v080_multi_mode"))e.putString("v080_multi_mode","Separate");if(!x.contains("v080_preset"))e.putString("v080_preset","Instagram 1:1");if(!x.contains("v080_exact"))e.putBoolean("v080_exact",false);if(!x.contains("v080_moment"))e.putString("v080_moment","All");if(!x.contains("v080_top_n"))e.putInt("v080_top_n",20);if(!x.contains("v080_cache_limit_mb"))e.putInt("v080_cache_limit_mb",2048);if(!x.contains("v080_show_hidden"))e.putBoolean("v080_show_hidden",false);e.apply();}

    private void fixVersion(View v){if(v==null)return;if(v instanceof TextView){TextView t=(TextView)v;String s=String.valueOf(t.getText());if(s.contains("v0.7"))t.setText(s.replace("v0.7.0","v0.8.0").replace("v0.7","v0.8"));}if(v instanceof ViewGroup){ViewGroup g=(ViewGroup)v;for(int i=0;i<g.getChildCount();i++)fixVersion(g.getChildAt(i));}}
    private void injectStudioTab(View v){if(!(v instanceof ViewGroup))return;ViewGroup g=(ViewGroup)v;if(g instanceof LinearLayout&&g.getParent() instanceof HorizontalScrollView){for(int i=0;i<g.getChildCount();i++)if(TAB.equals(g.getChildAt(i).getTag()))return;Button b=button80(tr80("Studio"));b.setTag(TAB);b.setOnClickListener(x->showStudio());g.addView(b);return;}for(int i=0;i<g.getChildCount();i++)injectStudioTab(g.getChildAt(i));}
    private void refreshExportProgress(){int q=queue==null?0:queue.count(V080ExportQueue.PENDING)+queue.count(V080ExportQueue.RUNNING);if(q>0){int pct=p().getInt("v080_export_progress",0);p().edit().putBoolean("export_pending_v050",true).putInt("v060_track_progress",pct).putString("v060_track_status",p().getString("v080_export_status",tr80("Render queue working"))).apply();}else p().edit().putBoolean("export_pending_v050",false).apply();}

    private void showStudio(){setCurrentPage("studio80");LinearLayout c=content();if(c==null)return;c.removeAllViews();c.addView(title(tr80("v0.8 Full Studio"),22));c.addView(note(tr80("Offline learned face identity • actor repair • multi-actor • preview • foreground queue • projects • storage • auto tuning")));
        ActorScanStore.ScanState s=scan();String key=projectKey();ArrayList<Uri> videos=videos();Uri out=outputTree();if(!key.isEmpty())studio.touchProject(key,videos,out==null?"":out.toString());
        addProjectCard(c,key,s,videos,out);addActorTools(c,key,s);addComposer(c,key,s,videos,out);addQueue(c);addStorage(c);addTuner(c);addSuggestions(c,key,s);}

    private void addProjectCard(LinearLayout c,String key,ActorScanStore.ScanState s,List<Uri> videos,Uri out){LinearLayout box=panel(tr80("Project & History"));box.addView(text(tr80("Current project")+": "+(key.isEmpty()?tr80("Not ready"):key.substring(0,Math.min(12,key.length()))),13,true));box.addView(text(tr80("Videos")+": "+videos.size()+"   •   "+tr80("Actor groups")+": "+(s==null?0:s.clusters.size()),13,false));box.addView(text(tr80("Output folder")+": "+(out==null?tr80("Not selected"):tr80("Selected")),13,false));List<String> recent=studio.recentProjectKeys();if(!recent.isEmpty()){box.addView(text(tr80("Recent projects"),13,true));for(int i=0;i<Math.min(6,recent.size());i++){String k=recent.get(i);box.addView(text("• "+k.substring(0,Math.min(16,k.length()))+(k.equals(key)?"  ✓":""),12,false));}}c.addView(box);}

    private void addActorTools(LinearLayout c,String key,ActorScanStore.ScanState s){LinearLayout box=panel(tr80("Advanced Actor Gallery"));if(s==null||s.clusters.isEmpty()){box.addView(note(tr80("Run Actor Scan first. v0.8 rebuilds the identity index with the bundled learned face model.")));c.addView(box);return;}LinkedHashSet<Integer> selected=studio.selectedActors(key);if(selected.isEmpty()){int id=selectedId();if(id>=0)selected.add(id);}boolean showHidden=p().getBoolean("v080_show_hidden",false);ArrayList<ActorScanStore.Cluster> xs=new ArrayList<>(s.clusters);xs.sort((a,b)->{boolean pa=isPinned(key,a.id),pb=isPinned(key,b.id);if(pa!=pb)return pa?-1:1;return Double.compare(b.smartScore(),a.smartScore());});
        CheckBox sh=new CheckBox(this);sh.setText(tr80("Show hidden actors"));sh.setChecked(showHidden);sh.setTextColor(textColor());sh.setOnClickListener(v->{p().edit().putBoolean("v080_show_hidden",sh.isChecked()).apply();showStudio();});box.addView(sh);
        for(ActorScanStore.Cluster a:xs){if(isHidden(key,a.id)&&!showHidden)continue;LinearLayout row=panelMini();CheckBox pick=new CheckBox(this);pick.setChecked(selected.contains(a.id));pick.setText((isPinned(key,a.id)?"★ ":"")+studio.actorName(key,a.id));pick.setTextColor(textColor());pick.setOnClickListener(v->{LinkedHashSet<Integer> set=studio.selectedActors(key);if(pick.isChecked())set.add(a.id);else set.remove(a.id);studio.saveSelectedActors(key,set);});row.addView(pick);long screen=Math.round(a.hits.size()*Math.max(350,scanSample(s)));row.addView(text(String.format(Locale.US,"%s %d • %s %d • %s %.0f%% • ≈%.1fs",tr80("Detections"),a.count,tr80("Videos"),a.videosSeen.size(),tr80("Quality"),a.avgQuality()*100,screen/1000.0),11,false));
            LinearLayout buttons=new LinearLayout(this);buttons.setOrientation(LinearLayout.HORIZONTAL);Button rename=smallButton(tr80("Rename"));rename.setOnClickListener(v->renameActor(key,a.id));buttons.addView(rename);Button pin=smallButton(isPinned(key,a.id)?tr80("Unpin"):tr80("Pin"));pin.setOnClickListener(v->{setFlag("pin",key,a.id,!isPinned(key,a.id));showStudio();});buttons.addView(pin);Button hide=smallButton(isHidden(key,a.id)?tr80("Unhide"):tr80("Hide"));hide.setOnClickListener(v->{setFlag("hide",key,a.id,!isHidden(key,a.id));showStudio();});buttons.addView(hide);row.addView(buttons);box.addView(row);}
        LinearLayout actions=new LinearLayout(this);actions.setOrientation(LinearLayout.HORIZONTAL);Button merge=smallButton(tr80("Merge selected"));merge.setOnClickListener(v->mergeSelected(key));actions.addView(merge);Button split=smallButton(tr80("Split weak matches"));split.setOnClickListener(v->splitSelected(key));actions.addView(split);box.addView(actions);
        LinearLayout feedback=new LinearLayout(this);feedback.setOrientation(LinearLayout.HORIZONTAL);Button correct=smallButton(tr80("Correct Actor"));correct.setOnClickListener(v->feedbackSelected(key,true));feedback.addView(correct);Button wrong=smallButton(tr80("Wrong Actor"));wrong.setOnClickListener(v->feedbackSelected(key,false));feedback.addView(wrong);box.addView(feedback);box.addView(note(tr80("Merge combines duplicate identity groups. Split moves low-confidence hits into a review group. Corrections also tune the project similarity threshold.")));c.addView(box);}

    private void addComposer(LinearLayout c,String key,ActorScanStore.ScanState s,List<Uri> videos,Uri out){LinearLayout box=panel(tr80("Smart Clip Composer"));SharedPreferences x=p();String[] presets={"Telegram Sticker Video","Instagram 1:1","Instagram 4:5","Story / Reels 9:16","Original","Maximum Quality 1:1"};box.addView(text(tr80("Export preset"),12,true));Spinner preset=spinner(presets,x.getString("v080_preset","Instagram 1:1"));preset.setOnItemSelectedListener(listener(pos->x.edit().putString("v080_preset",presets[pos]).apply()));box.addView(preset);
        String[] modes={"Separate","Together only"};box.addView(text(tr80("Multi-actor mode"),12,true));Spinner mode=spinner(modes,x.getString("v080_multi_mode","Separate"));mode.setOnItemSelectedListener(listener(pos->x.edit().putString("v080_multi_mode",modes[pos]).apply()));box.addView(mode);
        String[] moments={"All","Talking","Reaction","Action","Close-up","Silent reaction"};box.addView(text(tr80("Moment filter"),12,true));Spinner moment=spinner(moments,x.getString("v080_moment","All"));moment.setOnItemSelectedListener(listener(pos->x.edit().putString("v080_moment",moments[pos]).apply()));box.addView(moment);
        CheckBox exact=new CheckBox(this);exact.setText(tr80("Exact selected clip duration when source permits"));exact.setTextColor(textColor());exact.setChecked(x.getBoolean("v080_exact",false));exact.setOnClickListener(v->x.edit().putBoolean("v080_exact",exact.isChecked()).apply());box.addView(exact);
        box.addView(text(tr80("Top ranked clips per video"),12,true));String[] tops={"All","10","20","30","50"};String sv=x.getInt("v080_top_n",20)<=0?"All":String.valueOf(x.getInt("v080_top_n",20));Spinner top=spinner(tops,sv);top.setOnItemSelectedListener(listener(pos->x.edit().putInt("v080_top_n",pos==0?0:Integer.parseInt(tops[pos])).apply()));box.addView(top);
        LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);Button preview=smallButton(tr80("Before / After Preview"));preview.setOnClickListener(v->previewCurrent(key,s,videos));row.addView(preview);Button compose=smallButton(tr80("Build Render Queue"));compose.setOnClickListener(v->composeQueue(key,s,videos,out));row.addView(compose);box.addView(row);box.addView(note(tr80("Ranking combines face quality, identity confidence, actor density and camera stability. Duplicate windows are removed before they enter the queue.")));c.addView(box);}

    private void addQueue(LinearLayout c){LinearLayout box=panel(tr80("Export Queue & Recovery"));ArrayList<V080ExportQueue.Job> jobs=queue.load();int pending=0,running=0,done=0,failed=0,paused=0;for(V080ExportQueue.Job j:jobs){if(V080ExportQueue.PENDING.equals(j.state))pending++;else if(V080ExportQueue.RUNNING.equals(j.state))running++;else if(V080ExportQueue.DONE.equals(j.state))done++;else if(V080ExportQueue.FAILED.equals(j.state))failed++;else if(V080ExportQueue.PAUSED.equals(j.state))paused++;}box.addView(text("Pending "+pending+" • Running "+running+" • Done "+done+" • Failed "+failed+" • Paused "+paused,13,true));for(int i=0;i<Math.min(10,jobs.size());i++){V080ExportQueue.Job j=jobs.get(jobs.size()-1-i);box.addView(text(j.state+" • "+j.outputName+(j.error.isEmpty()?"":" • "+j.error),11,false));}
        LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.HORIZONTAL);Button start=smallButton(tr80("Start / Resume"));start.setOnClickListener(v->{queue.resumePaused();startExportService(V080ExportService.ACTION_START);});r.addView(start);Button pause=smallButton(tr80("Pause"));pause.setOnClickListener(v->startExportService(V080ExportService.ACTION_PAUSE));r.addView(pause);Button retry=smallButton(tr80("Retry Failed"));retry.setOnClickListener(v->{queue.retryFailed();startExportService(V080ExportService.ACTION_START);showStudio();});r.addView(retry);box.addView(r);Button clean=smallButton(tr80("Clear completed queue items"));clean.setOnClickListener(v->{queue.clearCompleted();showStudio();});box.addView(clean);if(paused+pending+failed>0)box.addView(note(tr80("Interrupted jobs are kept privately and restored after the app/process is restarted.")));c.addView(box);}

    private void addStorage(LinearLayout c){LinearLayout box=panel(tr80("Storage Manager"));ActorScanStore st=new ActorScanStore(this);long cache=st.cacheBytes();long privateBytes=V080StudioStore.bytes(getFilesDir());box.addView(text(String.format(Locale.US,"%s: %.1f MB",tr80("Actor cache"),cache/1048576.0),13,false));box.addView(text(String.format(Locale.US,"%s: %.1f MB",tr80("Private app data"),privateBytes/1048576.0),13,false));String[] limits={"512 MB","1024 MB","2048 MB","4096 MB"};String cur=p().getInt("v080_cache_limit_mb",2048)+" MB";Spinner lim=spinner(limits,cur);lim.setOnItemSelectedListener(listener(pos->p().edit().putInt("v080_cache_limit_mb",Integer.parseInt(limits[pos].split(" ")[0])).apply()));box.addView(lim);Button clean=smallButton(tr80("Safe cleanup old cache"));clean.setOnClickListener(v->worker80.execute(()->{long limit=p().getInt("v080_cache_limit_mb",2048)*1048576L;long left=st.trimToBytes(limit);queue.clearCompleted();runOnUiThread(()->{Toast.makeText(this,String.format(Locale.US,"Cache %.1f MB",left/1048576.0),Toast.LENGTH_SHORT).show();showStudio();});}));box.addView(clean);c.addView(box);}

    private void addTuner(LinearLayout c){LinearLayout box=panel(tr80("Auto Performance Tuner"));box.addView(text(tr80("Hardware codecs")+": "+V070CodecAdvisor.hardwareSummary(),12,false));Button tune=smallButton(tr80("Tune this phone automatically"));tune.setOnClickListener(v->autoTune());box.addView(tune);box.addView(note(tr80("The tuner chooses scan density, tracking density, cache behavior and codec policy from CPU/RAM/hardware encoder capability. You can still override every setting later.")));c.addView(box);}
    private void addSuggestions(LinearLayout c,String key,ActorScanStore.ScanState s){LinearLayout box=panel(tr80("Smart Suggestions"));box.addView(note(studio.suggestions(key,s,new ActorScanStore(this).cacheBytes(),V070CodecAdvisor.bestCodec(p())));c.addView(box);}

    private void renameActor(String key,int id){EditText e=new EditText(this);e.setText(studio.actorName(key,id));new AlertDialog.Builder(this).setTitle(tr80("Rename Actor")).setView(e).setNegativeButton(tr80("Cancel"),null).setPositiveButton(tr80("Save"),(d,w)->{studio.setActorName(key,id,e.getText().toString());showStudio();}).show();}
    private void mergeSelected(String key){ActorScanStore.ScanState s=scan();LinkedHashSet<Integer> ids=studio.selectedActors(key);if(s==null||ids.size()<2){toast(tr80("Select at least two actors"));return;}new AlertDialog.Builder(this).setTitle(tr80("Merge selected actors?" )).setMessage(tr80("The first selected actor becomes the master group. This can be undone only by rescanning." )).setNegativeButton(tr80("Cancel"),null).setPositiveButton(tr80("Merge"),(d,w)->worker80.execute(()->{try{Iterator<Integer>it=ids.iterator();int masterId=it.next();ActorScanStore.Cluster master=s.byId(masterId);if(master==null)return;while(it.hasNext()){int id=it.next();ActorScanStore.Cluster other=s.byId(id);if(other==null)continue;merge(master,other);s.clusters.remove(other);}s.selectedClusterId=masterId;setSelectedId(masterId);new ActorScanStore(this).save(s);studio.saveSelectedActors(key,Collections.singleton(masterId));runOnUiThread(this::showStudio);}catch(Throwable e){runOnUiThread(()->toast("Merge: "+e.getClass().getSimpleName()));}})).show();}
    private void merge(ActorScanStore.Cluster a,ActorScanStore.Cluster b){int ca=Math.max(1,a.count),cb=Math.max(1,b.count);if(a.centroid==null)a.centroid=b.centroid==null?null:b.centroid.clone();else if(b.centroid!=null&&a.centroid.length==b.centroid.length){for(int i=0;i<a.centroid.length;i++)a.centroid[i]=(a.centroid[i]*ca+b.centroid[i]*cb)/(ca+cb);FaceEngine.normalize(a.centroid);}a.count+=b.count;a.qualitySum+=b.qualitySum;a.hits.addAll(b.hits);a.hits.sort(Comparator.comparingLong(h->h.t));a.videosSeen.addAll(b.videosSeen);a.thumbs.addAll(b.thumbs);a.thumbQualities.addAll(b.thumbQualities);while(a.thumbs.size()>8)a.thumbs.remove(a.thumbs.size()-1);while(a.thumbQualities.size()>8)a.thumbQualities.remove(a.thumbQualities.size()-1);a.lastSeenMs=Math.max(a.lastSeenMs,b.lastSeenMs);}
    private void splitSelected(String key){ActorScanStore.ScanState s=scan();LinkedHashSet<Integer> ids=studio.selectedActors(key);if(s==null||ids.isEmpty()){toast(tr80("Select one actor first"));return;}int id=ids.iterator().next();ActorScanStore.Cluster src=s.byId(id);if(src==null)return;float threshold=Math.max(.42f,p().getFloat("cluster_threshold",.58f));ArrayList<ActorScanStore.Hit> weak=new ArrayList<>();for(ActorScanStore.Hit h:src.hits)if(h.score<threshold-.03f)weak.add(h);if(weak.size()<2||weak.size()>=src.hits.size()*.75){toast(tr80("No safe weak-match split found"));return;}worker80.execute(()->{try{int nid=0;for(ActorScanStore.Cluster q:s.clusters)nid=Math.max(nid,q.id+1);ActorScanStore.Cluster n=new ActorScanStore.Cluster(nid);n.centroid=src.centroid==null?null:src.centroid.clone();for(ActorScanStore.Hit h:weak){n.hits.add(h);n.videosSeen.add(h.videoIndex);n.qualitySum+=h.quality;}n.count=weak.size();src.hits.removeAll(weak);src.count=Math.max(1,src.hits.size());src.qualitySum=0;for(ActorScanStore.Hit h:src.hits)src.qualitySum+=h.quality;s.clusters.add(n);new ActorScanStore(this).save(s);runOnUiThread(this::showStudio);}catch(Throwable e){runOnUiThread(()->toast("Split: "+e.getClass().getSimpleName()));}});}
    private void feedbackSelected(String key,boolean correct){LinkedHashSet<Integer> ids=studio.selectedActors(key);if(ids.isEmpty()){int id=selectedId();if(id>=0)ids.add(id);}if(ids.isEmpty()){toast(tr80("Select an actor first"));return;}for(int id:ids)studio.feedback(key,id,correct?"correct":"wrong");float th=p().getFloat("cluster_threshold",.58f);th+=correct?-.006f:.012f;th=Math.max(.48f,Math.min(.78f,th));p().edit().putFloat("cluster_threshold",th).apply();toast(tr80("Correction learned for this project"));}

    private void composeQueue(String key,ActorScanStore.ScanState s,List<Uri> videos,Uri out){if(key.isEmpty()||s==null){toast(tr80("Run Actor Scan first"));return;}if(out==null){toast(tr80("Choose output folder first"));return;}LinkedHashSet<Integer> selected=studio.selectedActors(key);if(selected.isEmpty()){int id=selectedId();if(id>=0)selected.add(id);}if(selected.isEmpty()){toast(tr80("Select an actor first"));return;}final LinkedHashSet<Integer> ids=new LinkedHashSet<>(selected);worker80.execute(()->{try{ArrayList<V080ExportQueue.Job> jobs=new ArrayList<>();String mode=p().getString("v080_multi_mode","Separate");boolean together="Together only".equals(mode);long clip=Math.max(2000,p().getInt("clip_seconds",5)*1000L);boolean exact=p().getBoolean("v080_exact",false);String moment=p().getString("v080_moment","All");int top=p().getInt("v080_top_n",20);String preset=p().getString("v080_preset","Instagram 1:1");String aspect=aspectForPreset(preset);String codec=codecForPreset(preset);boolean track=p().getBoolean("smart_tracking",true);boolean safe=p().getBoolean("safe_zone",true);boolean max=p().getBoolean("max_quality",true)||preset.startsWith("Maximum");for(int vi=0;vi<videos.size();vi++){long duration=duration(videos.get(vi));if(duration<2000)continue;if(together){addJobsFor(jobs,key,videos.get(vi),out,vi,s,ids,true,clip,exact,moment,top,preset,aspect,codec,track,safe,max);}else for(int id:ids)addJobsFor(jobs,key,videos.get(vi),out,vi,s,Collections.singleton(id),false,clip,exact,moment,top,preset,aspect,codec,track,safe,max);}if(jobs.isEmpty())throw new IllegalStateException("No qualifying clips");queue.append(jobs);studio.saveSelectedActors(key,ids);runOnUiThread(()->new AlertDialog.Builder(this).setTitle(tr80("Render Queue Ready")).setMessage(jobs.size()+" "+tr80("ranked clip(s) added")).setNegativeButton(tr80("Later"),null).setPositiveButton(tr80("Start now"),(d,w)->startExportService(V080ExportService.ACTION_START)).show());}catch(Throwable e){runOnUiThread(()->toast(tr80("Queue build failed")+": "+e.getMessage()));}});}
    private void addJobsFor(List<V080ExportQueue.Job> outJobs,String key,Uri uri,Uri outTree,int vi,ActorScanStore.ScanState s,Collection<Integer> ids,boolean together,long clip,boolean exact,String moment,int top,String preset,String aspect,String codec,boolean track,boolean safe,boolean max){ArrayList<ActorScanStore.Hit> hits=V080SceneAnalyzer.collect(s,ids,vi,together);List<V080SceneAnalyzer.Segment> segs=V080SceneAnalyzer.build(hits,duration(uri),clip,scanSample(s),exact,moment,top);String idText=joinIds(ids);int no=0;for(V080SceneAnalyzer.Segment seg:segs){V080ExportQueue.Job j=new V080ExportQueue.Job();j.projectKey=key;j.sourceUri=uri.toString();j.outputTree=outTree.toString();j.videoIndex=vi;j.actorIds=idText;j.mode=together?"together":"separate";j.startMs=seg.startMs;j.endMs=seg.endMs;j.score=seg.score;j.aspect=aspect;j.preset=preset;j.codec=codec;j.tracking=track;j.safeZone=safe;j.maxQuality=max;j.outputName=String.format(Locale.US,"%s_%s_A%s_%02d_%dms.mp4",seg.rank,safeBase(displayName(uri)),idText.replace(',','-'),++no,seg.startMs);outJobs.add(j);}}

    private void previewCurrent(String key,ActorScanStore.ScanState s,List<Uri> videos){if(s==null||videos.isEmpty()){toast(tr80("Scan and select videos first"));return;}LinkedHashSet<Integer> ids=studio.selectedActors(key);if(ids.isEmpty()){int id=selectedId();if(id>=0)ids.add(id);}if(ids.isEmpty()){toast(tr80("Select an actor first"));return;}final LinkedHashSet<Integer> chosen=new LinkedHashSet<>(ids);worker80.execute(()->{Bitmap original=null,cropped=null;MediaMetadataRetriever mr=new MediaMetadataRetriever();try{Uri uri=videos.get(0);boolean together="Together only".equals(p().getString("v080_multi_mode","Separate"));ArrayList<ActorScanStore.Hit> hits=V080SceneAnalyzer.collect(s,chosen,0,together);List<V080SceneAnalyzer.Segment> segs=V080SceneAnalyzer.build(hits,duration(uri),Math.max(2000,p().getInt("clip_seconds",5)*1000L),scanSample(s),p().getBoolean("v080_exact",false),p().getString("v080_moment","All"),1);if(segs.isEmpty())throw new IllegalStateException("No preview scene");V080SceneAnalyzer.Segment seg=segs.get(0);long mid=(seg.startMs+seg.endMs)/2;mr.setDataSource(this,uri);original=mr.getFrameAtTime(mid*1000L,MediaMetadataRetriever.OPTION_CLOSEST);if(original==null)throw new IOException("Frame unavailable");cropped=previewCrop(original,seg.hits,aspectForPreset(p().getString("v080_preset","Instagram 1:1")));Bitmap a=original,b=cropped;runOnUiThread(()->showPreviewDialog(a,b,seg));original=null;cropped=null;}catch(Throwable e){Bitmap a=original,b=cropped;if(a!=null)a.recycle();if(b!=null&&b!=a)b.recycle();runOnUiThread(()->toast(tr80("Preview failed")+": "+e.getClass().getSimpleName()));}finally{try{mr.release();}catch(Throwable ignored){}}});}
    private Bitmap previewCrop(Bitmap src,List<ActorScanStore.Hit> hits,String aspectName){float target="Original".equals(aspectName)?src.getWidth()/(float)src.getHeight():aspectValue(aspectName);double sx=0,sy=0,w=0;for(ActorScanStore.Hit h:hits){double q=.2+h.quality;sx+=h.cx*q;sy+=h.cy*q;w+=q;}float cx=w==0?.5f:(float)(sx/w),cy=w==0?.5f:(float)(sy/w);int sw=src.getWidth(),sh=src.getHeight(),cw=sw,ch=sh;if(sw/(float)sh>target)cw=Math.max(1,Math.round(sh*target));else ch=Math.max(1,Math.round(sw/target));int x=Math.round(cx*sw-cw/2f),y=Math.round(cy*sh-ch*.42f);x=Math.max(0,Math.min(sw-cw,x));y=Math.max(0,Math.min(sh-ch,y));return Bitmap.createBitmap(src,x,y,cw,ch);}
    private void showPreviewDialog(Bitmap original,Bitmap crop,V080SceneAnalyzer.Segment seg){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(8),dp(8),dp(8),dp(8));box.addView(text(tr80("Original"),12,true));ImageView a=new ImageView(this);a.setAdjustViewBounds(true);a.setImageBitmap(original);box.addView(a,new LinearLayout.LayoutParams(-1,dp(190)));box.addView(text(tr80("Smart Crop Preview")+" • "+seg.rank+" "+Math.round(seg.score)+"/100 • "+seg.expression,12,true));ImageView b=new ImageView(this);b.setAdjustViewBounds(true);b.setScaleType(ImageView.ScaleType.CENTER_INSIDE);b.setImageBitmap(crop);box.addView(b,new LinearLayout.LayoutParams(-1,dp(220)));AlertDialog d=new AlertDialog.Builder(this).setTitle(tr80("Before / After")).setView(box).setPositiveButton("OK",null).create();d.setOnDismissListener(x->{try{if(original!=null&&!original.isRecycled())original.recycle();}catch(Throwable ignored){}try{if(crop!=null&&crop!=original&&!crop.isRecycled())crop.recycle();}catch(Throwable ignored){}});d.show();}

    private void autoTune(){worker80.execute(()->{try{android.app.ActivityManager am=(android.app.ActivityManager)getSystemService(ACTIVITY_SERVICE);android.app.ActivityManager.MemoryInfo mi=new android.app.ActivityManager.MemoryInfo();am.getMemoryInfo(mi);int cores=Runtime.getRuntime().availableProcessors();long gb=mi.totalMem/(1024L*1024*1024);String mode=(cores>=8&&gb>=6)?"Balanced":(cores>=6&&gb>=4)?"Balanced":"Quick";boolean hevc=V070CodecAdvisor.hasHardware("video/hevc");p().edit().putString("speed_mode_v070",mode).putBoolean("two_pass_scan_v070",true).putBoolean("landmark_on_demand_v070",true).putBoolean("incremental_cache_v070",true).putBoolean("parallel_prefetch_v070",cores>=6).putString("tracking_motion_v061",cores>=8?"Slow":"Fixed actor average").putBoolean("dynamic_zoom_v050",false).putString("codec_best_v070",hevc?"HEVC":"AVC").apply();String msg="CPU "+cores+" • RAM ~"+gb+" GB • "+V070CodecAdvisor.hardwareSummary()+"\n"+tr80("Recommended")+": "+mode+" / "+(hevc?"HEVC":"AVC");runOnUiThread(()->new AlertDialog.Builder(this).setTitle(tr80("Auto Tune Complete")).setMessage(msg).setPositiveButton("OK",null).show());}catch(Throwable e){runOnUiThread(()->toast("Tune: "+e.getClass().getSimpleName()));}});}

    private void startExportService(String action){Intent i=new Intent(this,V080ExportService.class).setAction(action);if(Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);toast(tr80("Render service updated"));ui80.postDelayed(this::showStudio,600);}
    private void touchCurrentProject(){try{String k=projectKey();Uri o=outputTree();if(!k.isEmpty())studio.touchProject(k,videos(),o==null?"":o.toString());}catch(Throwable ignored){}}

    @SuppressWarnings("unchecked") private ArrayList<Uri> videos(){try{Field f=MainActivity.class.getDeclaredField("videos");f.setAccessible(true);return new ArrayList<>((ArrayList<Uri>)f.get(this));}catch(Throwable e){return new ArrayList<>();}}
    private ActorScanStore.ScanState scan(){try{Field f=MainActivity.class.getDeclaredField("scanState");f.setAccessible(true);return(ActorScanStore.ScanState)f.get(this);}catch(Throwable e){return null;}}
    private int selectedId(){try{Field f=MainActivity.class.getDeclaredField("selectedClusterId");f.setAccessible(true);return f.getInt(this);}catch(Throwable e){return-1;}}
    private void setSelectedId(int id){try{Field f=MainActivity.class.getDeclaredField("selectedClusterId");f.setAccessible(true);f.setInt(this,id);}catch(Throwable ignored){}}
    private Uri outputTree(){try{Field f=MainActivity.class.getDeclaredField("outputTree");f.setAccessible(true);return(Uri)f.get(this);}catch(Throwable e){return null;}}
    private LinearLayout content(){try{Field f=MainActivity.class.getDeclaredField("content");f.setAccessible(true);return(LinearLayout)f.get(this);}catch(Throwable e){return null;}}
    private void setCurrentPage(String s){try{Field f=MainActivity.class.getDeclaredField("currentPage");f.setAccessible(true);f.set(this,s);}catch(Throwable ignored){}}
    private String projectKey(){try{Field f=MainActivity.class.getDeclaredField("currentProjectKey");f.setAccessible(true);String k=(String)f.get(this);if(k!=null&&!k.isEmpty())return k;}catch(Throwable ignored){}try{Method m=MainActivity.class.getDeclaredMethod("computeProjectKey");m.setAccessible(true);String k=(String)m.invoke(this);try{Field f=MainActivity.class.getDeclaredField("currentProjectKey");f.setAccessible(true);f.set(this,k);}catch(Throwable ignored){}return k;}catch(Throwable e){return"";}}
    private long scanSample(ActorScanStore.ScanState s){return s==null?900:Math.max(350,s.sampleMs);}

    private void setFlag(String n,String key,int id,boolean v){p().edit().putBoolean("v080_"+n+"_"+key+"_"+id,v).apply();}private boolean isPinned(String k,int id){return p().getBoolean("v080_pin_"+k+"_"+id,false);}private boolean isHidden(String k,int id){return p().getBoolean("v080_hide_"+k+"_"+id,false);}
    private long duration(Uri uri){MediaMetadataRetriever m=new MediaMetadataRetriever();try{m.setDataSource(this,uri);String x=m.extractMetadata(MediaMetadataRetriever.METADATA_KEY_DURATION);return x==null?-1:Long.parseLong(x);}catch(Throwable e){return-1;}finally{try{m.release();}catch(Throwable ignored){}}}
    private String displayName(Uri u){try(Cursor c=getContentResolver().query(u,new String[]{OpenableColumns.DISPLAY_NAME},null,null,null)){if(c!=null&&c.moveToFirst()){String s=c.getString(0);if(s!=null&&!s.isEmpty())return s;}}catch(Throwable ignored){}return u.getLastPathSegment()==null?"video":u.getLastPathSegment();}
    private String safeBase(String n){int d=n.lastIndexOf('.');if(d>0)n=n.substring(0,d);return n.replaceAll("[^A-Za-z0-9._-]+","_");}
    private String joinIds(Collection<Integer> ids){StringBuilder b=new StringBuilder();for(int id:ids){if(b.length()>0)b.append(',');b.append(id);}return b.toString();}
    private String aspectForPreset(String p){if(p==null)return"1:1";if(p.contains("4:5"))return"4:5";if(p.contains("9:16")||p.contains("Reels")||p.contains("Story"))return"9:16";if(p.startsWith("Original"))return"Original";return"1:1";}private String codecForPreset(String p){if(p!=null&&p.contains("Telegram"))return"AVC";return"Auto";}private float aspectValue(String s){if("9:16".equals(s))return 9f/16f;if("4:5".equals(s))return 4f/5f;if("16:9".equals(s))return 16f/9f;return 1f;}

    private LinearLayout panel(String heading){LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.setPadding(dp(12),dp(10),dp(12),dp(10));b.setBackground(round(cardColor(),borderColor(),16));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(6),0,dp(6));b.setLayoutParams(lp);b.addView(title(heading,17));return b;}private LinearLayout panelMini(){LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.setPadding(dp(8),dp(6),dp(8),dp(6));b.setBackground(round(cardColor(),borderColor(),12));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(3),0,dp(3));b.setLayoutParams(lp);return b;}
    private TextView title(String s,int sp){return text(s,sp,true);}private TextView text(String s,int sp,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setTextColor(textColor());if(bold)t.setTypeface(null,1);t.setPadding(dp(3),dp(4),dp(3),dp(4));return t;}private TextView note(String s){TextView t=text(s,12,false);t.setTextColor(subColor());return t;}private Button button80(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(Color.WHITE);b.setBackground(round(accentColor(),accentColor(),13));return b;}private Button smallButton(String s){Button b=button80(s);b.setTextSize(11);b.setMinHeight(dp(38));b.setPadding(dp(7),dp(3),dp(7),dp(3));return b;}private Spinner spinner(String[] items,String saved){Spinner s=new Spinner(this);s.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,items));for(int i=0;i<items.length;i++)if(items[i].equals(saved)){s.setSelection(i);break;}return s;}private AdapterView.OnItemSelectedListener listener(java.util.function.IntConsumer c){return new AdapterView.OnItemSelectedListener(){public void onItemSelected(AdapterView<?>a,View v,int pos,long id){c.accept(pos);}public void onNothingSelected(AdapterView<?>a){}};}
    private GradientDrawable round(int fill,int stroke,int r){GradientDrawable d=new GradientDrawable();d.setColor(fill);d.setCornerRadius(dp(r));d.setStroke(dp(1),stroke);return d;}private int textColor(){return"Dark".equals(p().getString("theme_v060","Dark"))?0xfff4f7fb:0xff172033;}private int subColor(){return"Dark".equals(p().getString("theme_v060","Dark"))?0xffaebbd0:0xff5b6474;}private int cardColor(){return"Dark".equals(p().getString("theme_v060","Dark"))?0xff151e2d:0xffffffff;}private int borderColor(){return"Dark".equals(p().getString("theme_v060","Dark"))?0xff29364b:0xffd8dee9;}private int accentColor(){String t=p().getString("theme_v060","Dark");if("Red".equals(t))return 0xffe11d48;if("Pink".equals(t))return 0xffdb2777;if("White".equals(t))return 0xff202938;return 0xff2563eb;}private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}

    private String tr80(String en){String l=p().getString("language_v060","en");if("en".equals(l))return en;Map<String,String[]>m=new HashMap<>();
        m.put("Studio",new String[]{"استودیو","Stüdyo","Студия"});m.put("v0.8 Full Studio",new String[]{"استودیوی کامل v0.8","v0.8 Tam Stüdyo","Полная студия v0.8"});m.put("Project & History",new String[]{"پروژه و تاریخچه","Proje ve Geçmiş","Проект и история"});m.put("Advanced Actor Gallery",new String[]{"گالری پیشرفته بازیگر","Gelişmiş Oyuncu Galerisi","Расширенная галерея актёров"});m.put("Smart Clip Composer",new String[]{"سازنده هوشمند کلیپ","Akıllı Klip Oluşturucu","Умный конструктор клипов"});m.put("Export Queue & Recovery",new String[]{"صف خروجی و بازیابی","Dışa Aktarma Kuyruğu ve Kurtarma","Очередь экспорта и восстановление"});m.put("Storage Manager",new String[]{"مدیریت حافظه","Depolama Yöneticisi","Хранилище"});m.put("Auto Performance Tuner",new String[]{"تنظیم خودکار عملکرد","Otomatik Performans Ayarı","Автонастройка производительности"});m.put("Smart Suggestions",new String[]{"پیشنهادهای هوشمند","Akıllı Öneriler","Умные рекомендации"});m.put("Before / After Preview",new String[]{"پیش‌نمایش قبل / بعد","Önce / Sonra Önizleme","До / После"});m.put("Build Render Queue",new String[]{"ساخت صف خروجی","Render Kuyruğu Oluştur","Создать очередь рендера"});m.put("Merge selected",new String[]{"ادغام انتخاب‌شده‌ها","Seçilenleri Birleştir","Объединить выбранных"});m.put("Split weak matches",new String[]{"جدا کردن تطبیق‌های ضعیف","Zayıf Eşleşmeleri Ayır","Разделить слабые совпадения"});m.put("Correct Actor",new String[]{"بازیگر درست","Doğru Oyuncu","Верный актёр"});m.put("Wrong Actor",new String[]{"بازیگر اشتباه","Yanlış Oyuncu","Неверный актёр"});m.put("Start / Resume",new String[]{"شروع / ادامه","Başlat / Devam","Старт / Продолжить"});m.put("Pause",new String[]{"توقف موقت","Duraklat","Пауза"});m.put("Retry Failed",new String[]{"تلاش دوباره ناموفق‌ها","Başarısızları Yeniden Dene","Повторить ошибки"});m.put("Safe cleanup old cache",new String[]{"پاکسازی امن کش قدیمی","Eski Önbelleği Güvenle Temizle","Безопасно очистить старый кэш"});m.put("Tune this phone automatically",new String[]{"تنظیم خودکار این گوشی","Bu Telefonu Otomatik Ayarla","Автонастройка телефона"});m.put("Render Queue Ready",new String[]{"صف خروجی آماده است","Render Kuyruğu Hazır","Очередь готова"});m.put("Start now",new String[]{"الان شروع کن","Şimdi Başlat","Запустить сейчас"});m.put("Later",new String[]{"بعداً","Daha Sonra","Позже"});m.put("Rename",new String[]{"تغییر نام","Yeniden Adlandır","Переименовать"});m.put("Pin",new String[]{"سنجاق","Sabitle","Закрепить"});m.put("Hide",new String[]{"مخفی","Gizle","Скрыть"});m.put("Save",new String[]{"ذخیره","Kaydet","Сохранить"});m.put("Cancel",new String[]{"لغو","İptal","Отмена"});m.put("Recommended",new String[]{"پیشنهادی","Önerilen","Рекомендуется"});
        String[]a=m.get(en);if(a==null)return en;return"fa".equals(l)?a[0]:"tr".equals(l)?a[1]:a[2];}
}
