package com.mhsx.actorsticker;

import android.app.*;
import android.content.*;
import android.graphics.Color;
import android.net.Uri;
import android.os.*;
import android.view.*;
import android.widget.*;

import androidx.media3.common.util.UnstableApi;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.util.*;
import java.util.concurrent.*;

/**
 * v0.9 Stability + Accuracy shell.
 * New v0.9 features are routed through V090AppController / Room queue / RecyclerView Gallery V2.
 * Face-follow is opt-in: the upgrade migration forcibly disables automatic pan/zoom until the user enables it.
 */
@UnstableApi
public class MainActivityV090 extends MainActivityV081 {
    private static final String TAB_STABILITY="v090_stability_tab",TAB_GALLERY="v090_gallery_tab",TAB_DIAG="v090_diag_tab";
    private final Handler ui90=new Handler(Looper.getMainLooper());
    private final ExecutorService worker90=Executors.newSingleThreadExecutor();
    private volatile boolean dead90;
    private V090AppController controller;
    private long lastGuard,lastWatchdog,scanToken;

    private final Runnable loop90=new Runnable(){@Override public void run(){if(dead90)return;try{View root=getWindow().getDecorView();fixVersion(root);injectTabs(root);rewire(root);runtimeTick();watchJobs();}catch(Throwable e){V090Diagnostics.log(MainActivityV090.this,"ui-loop",e);}ui90.postDelayed(this,500L);}};

    @Override public void onCreate(Bundle state){
        super.onCreate(state);
        controller=new V090AppController(this);
        applyFollowRuntime();
        ui90.post(loop90);
        if(!prefs90().getBoolean("face_benchmark_done_v090",false))worker90.execute(()->{try{V090FaceBenchmark.Result r=V090FaceBenchmark.run(this);runOnUiThread(()->Toast.makeText(this,String.format(Locale.US,"Face engine tuned: %d thread(s) • %.1f ms",r.threads,r.ms),Toast.LENGTH_LONG).show());}catch(Throwable e){V090Diagnostics.log(this,"first-run-benchmark",e);}});
    }
    @Override protected void onDestroy(){dead90=true;ui90.removeCallbacksAndMessages(null);worker90.shutdownNow();super.onDestroy();}

    private SharedPreferences prefs90(){return getSharedPreferences("actor_sticker",MODE_PRIVATE);}private int dp90(int x){return Math.round(x*getResources().getDisplayMetrics().density);}
    private int fg(){return"Dark".equals(prefs90().getString("theme_v060","Dark"))?0xfff4f7fb:0xff172033;}private int sub(){return"Dark".equals(prefs90().getString("theme_v060","Dark"))?0xffaebbd0:0xff596579;}private int card(){return"Dark".equals(prefs90().getString("theme_v060","Dark"))?0xff151e2d:0xffffffff;}private int accent(){String t=prefs90().getString("theme_v060","Dark");if("Red".equals(t))return 0xffe11d48;if("Pink".equals(t))return 0xffdb2777;return 0xff2563eb;}
    private TextView label(String s,int sp,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setTextColor(fg());if(bold)t.setTypeface(null,1);t.setPadding(dp90(5),dp90(5),dp90(5),dp90(5));return t;}private TextView note(String s){TextView t=label(s,12,false);t.setTextColor(sub());return t;}private Button button(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);return b;}
    private LinearLayout box(String title){LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.setPadding(dp90(12),dp90(10),dp90(12),dp90(10));b.setBackgroundColor(card());LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp90(6),0,dp90(6));b.setLayoutParams(lp);b.addView(label(title,17,true));return b;}

    private void fixVersion(View v){if(v==null)return;if(v instanceof TextView){TextView t=(TextView)v;String s=String.valueOf(t.getText());if(s.contains("v0.8.1"))t.setText(s.replace("v0.8.1","v0.9.0"));else if(s.contains("v0.8")&&!s.contains("v0.9"))t.setText(s.replace("v0.8","v0.9"));}if(v instanceof ViewGroup){ViewGroup g=(ViewGroup)v;for(int i=0;i<g.getChildCount();i++)fixVersion(g.getChildAt(i));}}
    private void injectTabs(View v){if(!(v instanceof ViewGroup))return;ViewGroup g=(ViewGroup)v;if(g instanceof LinearLayout&&g.getParent() instanceof HorizontalScrollView){boolean hasBase=false;for(int i=0;i<g.getChildCount();i++)if(g.getChildAt(i) instanceof Button){String s=norm(((Button)g.getChildAt(i)).getText().toString());if(s.contains("videos")||s.contains("ویدیو")||s.contains("video")){hasBase=true;break;}}if(hasBase){addTab((LinearLayout)g,TAB_GALLERY,"Gallery V2",x->showGalleryV2());addTab((LinearLayout)g,TAB_STABILITY,"Stability",x->showStability());addTab((LinearLayout)g,TAB_DIAG,"Diagnostics",x->showDiagnostics());return;}}for(int i=0;i<g.getChildCount();i++)injectTabs(g.getChildAt(i));}
    private void addTab(LinearLayout g,String tag,String text,View.OnClickListener click){for(int i=0;i<g.getChildCount();i++)if(tag.equals(g.getChildAt(i).getTag()))return;Button b=button(text);b.setTag(tag);b.setOnClickListener(click);g.addView(b);}

    private void rewire(View v){if(v==null)return;if(v instanceof Button){Button b=(Button)v;String s=norm(String.valueOf(b.getText()));if(isGallery(s))b.setOnClickListener(x->showGalleryV2());else if(isScan(s))b.setOnClickListener(x->startScan90(false));else if(isRefresh(s))b.setOnClickListener(x->new AlertDialog.Builder(this).setTitle("Refresh Full Scan?").setMessage("A recovery backup is saved first, then this project is re-indexed.").setNegativeButton("Cancel",null).setPositiveButton("Refresh",(d,w)->startScan90(true)).show());return;}if(v instanceof ViewGroup){ViewGroup g=(ViewGroup)v;for(int i=0;i<g.getChildCount();i++)rewire(g.getChildAt(i));}}
    private boolean isGallery(String s){return s.equals("actor gallery")||s.contains("open actor gallery")||s.contains("گالری بازیگر")||s.contains("oyuncu galer")||s.contains("галерея акт");}private boolean isScan(String s){return s.equals("scan actors")||s.contains("scan actors now")||s.contains("background scan / resume")||s.equals("start / resume scan")||s.equals("resume scan")||s.equals("1. scan actors")||s.contains("اسکن بازیگر")||s.contains("oyuncuları tara")||s.contains("скан акт");}private boolean isRefresh(String s){return s.equals("refresh full scan")||s.contains("اسکن کامل مجدد")||s.contains("tam taramayı yenile")||s.contains("полное пересканирование");}private String norm(String s){return s==null?"":s.trim().toLowerCase(Locale.ROOT);}

    private void startScan90(boolean refresh){ArrayList<Uri> vs=videos();if(vs.isEmpty()){Toast.makeText(this,"Add videos first",Toast.LENGTH_SHORT).show();return;}String key=projectKey();if(refresh&&!key.isEmpty())V090RecoveryManager.backupIndex(this,key,"before_refresh");scanToken=System.currentTimeMillis();if(!V090WorkController.startScan(this,refresh)){invokeBase("startActorScan",new Class[]{boolean.class},new Object[]{refresh});return;}prefs90().edit().putBoolean("bg_scan_running",true).putLong("bg_scan_updated",scanToken).apply();ui90.postDelayed(()->{long updated=prefs90().getLong("bg_scan_updated",0);boolean running=prefs90().getBoolean("bg_scan_running",false);if(!dead90&&scanToken>0&&(!running||updated<=scanToken)){V090Diagnostics.event(this,"scan-watchdog","service startup fallback");prefs90().edit().putBoolean("bg_scan_running",false).apply();invokeBase("startActorScan",new Class[]{boolean.class},new Object[]{refresh});}},5500L);}

    private void runtimeTick(){long now=System.currentTimeMillis();if(now-lastGuard<4500)return;lastGuard=now;V090RuntimeGuard.Snapshot s=V090RuntimeGuard.check(this);if(prefs90().getBoolean("safe_mode_v090",false))controller.applySafeMode();if(s.lowMemory)V090Diagnostics.event(this,"memory-guard","free="+s.freeMb+"MB");}
    private void watchJobs(){long now=System.currentTimeMillis();if(now-lastWatchdog<5000)return;lastWatchdog=now;if(prefs90().getBoolean("job_watchdog_v090",true)){int n=controller.queue.recoverStalled(18000L);if(n>0){V090Diagnostics.event(this,"job-watchdog","stalled="+n);Toast.makeText(this,n+" stalled job(s) detected",Toast.LENGTH_LONG).show();}}}

    private void showGalleryV2(){setPage("gallery_v2_090");LinearLayout c=content();if(c==null)return;c.removeAllViews();c.addView(label("Actor Gallery V2 • v0.9",21,true));c.addView(note("RecyclerView/ListAdapter • lazy thumbnails • safe snapshot • multi-angle references • wrong-person markers"));ActorScanStore.ScanState s=scan();if(s==null){c.addView(note("Actor index is not loaded yet."));Button scan=button("▶ Scan / Resume");scan.setOnClickListener(v->startScan90(false));c.addView(scan);loadStateThenGallery();return;}ArrayList<ActorScanStore.Cluster> clusters=snapshot(s);if(clusters.isEmpty()){c.addView(note("No actors indexed. Run Refresh Full Scan."));return;}int selected=selectedId();clusters.sort((a,b)->Double.compare(safeScore(b),safeScore(a)));
        List<String> suggestions=V090ReferenceBank.mergeSuggestions(s);if(!suggestions.isEmpty()){LinearLayout m=box("Possible duplicate actors");for(int i=0;i<Math.min(6,suggestions.size());i++)m.addView(note("• "+suggestions.get(i)));m.addView(note("Review both faces before using Studio → Merge selected."));c.addView(m);}
        ActorScanStore.Cluster sel=s.byId(selected);if(sel!=null){LinearLayout w=box("Wrong-person timeline");V090WrongPersonTimelineView view=new V090WrongPersonTimelineView(this);view.setHits(safeHits(sel));w.addView(view,new LinearLayout.LayoutParams(-1,dp90(100)));w.addView(note(view.suspicious()+" low-confidence marker(s). Red bars are places worth reviewing."));c.addView(w);}
        RecyclerView list=new RecyclerView(this);list.setLayoutManager(new LinearLayoutManager(this));list.setNestedScrollingEnabled(true);V090ActorAdapter adapter=new V090ActorAdapter(this,new V090ActorAdapter.Callback(){public void select(int id){selectActor(s,id);showGalleryV2();}public void buildReferences(int id){ActorScanStore.Cluster a=s.byId(id);if(a==null)return;Toast.makeText(MainActivityV090.this,"Building multi-angle references…",Toast.LENGTH_SHORT).show();worker90.execute(()->{int n=V090ReferenceBank.build(MainActivityV090.this,s,a);runOnUiThread(()->Toast.makeText(MainActivityV090.this,"Reference bank: "+n+" face(s)",Toast.LENGTH_LONG).show());});}});list.setAdapter(adapter);ArrayList<V090ActorAdapter.Item> items=new ArrayList<>();for(ActorScanStore.Cluster a:clusters){if(a==null||a.count<=0)continue;items.add(new V090ActorAdapter.Item(a.id,a.count,a.videosSeen.size(),a.avgQuality(),safeScore(a),a.id==selected,s.projectKey,safeThumbs(a)));if(items.size()>=120)break;}adapter.submitList(items);c.addView(list,new LinearLayout.LayoutParams(-1,dp90(620)));c.addView(note("Only visible rows decode thumbnails. This keeps large galleries from allocating every face bitmap at once."));}

    private void loadStateThenGallery(){worker90.execute(()->{try{String k=projectKey();ActorScanStore.ScanState s=new ActorScanStore(this).load(k);if(s!=null)setScan(s);}catch(Throwable e){V090Diagnostics.log(this,"gallery-load",e);}runOnUiThread(()->{if(!dead90&&"gallery_v2_090".equals(page()))showGalleryV2();});});}
    private ArrayList<ActorScanStore.Cluster> snapshot(ActorScanStore.ScanState s){for(int i=0;i<3;i++)try{return new ArrayList<>(s.clusters);}catch(Throwable e){try{Thread.sleep(20);}catch(Throwable ignored){}}return new ArrayList<>();}private ArrayList<ActorScanStore.Hit> safeHits(ActorScanStore.Cluster a){try{ArrayList<ActorScanStore.Hit>x=new ArrayList<>(a.hits);x.sort(Comparator.comparingLong(h->h.t));return x;}catch(Throwable e){return new ArrayList<>();}}private ArrayList<String> safeThumbs(ActorScanStore.Cluster a){try{return new ArrayList<>(a.thumbs);}catch(Throwable e){return new ArrayList<>();}}private double safeScore(ActorScanStore.Cluster a){try{return a.smartScore();}catch(Throwable e){return 0;}}
    private void selectActor(ActorScanStore.ScanState s,int id){setSelectedId(id);s.selectedClusterId=id;worker90.execute(()->{try{new ActorScanStore(this).save(s);}catch(Throwable e){V090Diagnostics.log(this,"select-actor",e);}});}

    private void showStability(){setPage("stability_v090");LinearLayout c=content();if(c==null)return;c.removeAllViews();c.addView(label("Stability + Tracking Control • v0.9",21,true));c.addView(note("Automatic face-follow is OFF by default. The frame stays fixed at the actor's average position until you explicitly enable it."));
        LinearLayout follow=box("Camera / Face Follow");Switch sw=new Switch(this);sw.setText("Enable automatic Face Follow");sw.setTextColor(fg());sw.setChecked(controller.faceFollow());follow.addView(sw);TextView state=note(controller.faceFollow()?"ON • crop may move smoothly":"OFF • Fixed actor average • no automatic pan/zoom");follow.addView(state);sw.setOnCheckedChangeListener((b,on)->{controller.setFaceFollow(on);if(!on)prefs90().edit().putBoolean("manual_path_v090",false).apply();applyFollowRuntime();showStability();});Switch cine=new Switch(this);cine.setText("Cinematic Follow (only when Face Follow is ON)");cine.setTextColor(fg());cine.setChecked(prefs90().getBoolean("cinematic_follow_v090",false));cine.setEnabled(controller.faceFollow());cine.setOnCheckedChangeListener((b,on)->{prefs90().edit().putBoolean("cinematic_follow_v090",on).putString("tracking_motion_v061",on?"Custom":"Slow").apply();applyFollowRuntime();});follow.addView(cine);follow.addView(note("Cinematic mode uses a large dead-zone and maximum pan speed; small face movements do not move the frame."));addSeek(follow,"Cinematic max pan speed",1,35,prefs90().getInt("cinematic_speed_v090",10),v->{prefs90().edit().putInt("cinematic_speed_v090",v).apply();applyFollowRuntime();});addSeek(follow,"Cinematic dead zone",4,30,prefs90().getInt("cinematic_deadzone_v090",16),v->{prefs90().edit().putInt("cinematic_deadzone_v090",v).apply();applyFollowRuntime();});c.addView(follow);

        LinearLayout path=box("Tracking Path Editor");Switch manual=new Switch(this);manual.setText("Enable manual camera path");manual.setTextColor(fg());manual.setChecked(prefs90().getBoolean("manual_path_v090",false));path.addView(manual);ActorScanStore.Cluster actor=selectedActor();V090TrackingPathView pv=new V090TrackingPathView(this);pv.setSpec(prefs90().getString("tracking_path_v090","0:0.5:0.42;0.5:0.5:0.42;1:0.5:0.42"));if(actor!=null)pv.setHits(safeHits(actor));pv.setListener(spec->{prefs90().edit().putString("tracking_path_v090",spec).apply();applyFollowRuntime();});path.addView(pv,new LinearLayout.LayoutParams(-1,dp90(190)));manual.setOnCheckedChangeListener((b,on)->{prefs90().edit().putBoolean("manual_path_v090",on).apply();applyFollowRuntime();});addSeek(path,"Freeze frame after % of clip",0,100,prefs90().getInt("tracking_freeze_v090",100),v->{prefs90().edit().putInt("tracking_freeze_v090",v).apply();applyFollowRuntime();});path.addView(note("Drag the three red points. Grey line = detected actor path; blue/red path = your camera path. 100% freeze means no early freeze."));c.addView(path);

        LinearLayout preview=box("Real 4-second Preview");Button pr=button("▶ Render 4s Before-Export Preview");pr.setOnClickListener(v->renderPreview());preview.addView(pr);preview.addView(note("This creates a temporary MP4 using the same crop/tracking engine, then plays it. The temporary preview is deleted when you close it."));c.addView(preview);

        LinearLayout guards=box("Reliability Guards");CheckBox watchdog=check("Job watchdog • detect STALLED jobs",prefs90().getBoolean("job_watchdog_v090",true));CheckBox quality=check("Face Quality Gate before embedding",prefs90().getBoolean("quality_gate_v090",true));CheckBox memory=check("Memory Guard",prefs90().getBoolean("memory_guard_v090",true));CheckBox thermal=check("Thermal Adaptive Mode",prefs90().getBoolean("thermal_adaptive_v090",true));guards.addView(watchdog);guards.addView(quality);guards.addView(memory);guards.addView(thermal);View.OnClickListener save=v->prefs90().edit().putBoolean("job_watchdog_v090",watchdog.isChecked()).putBoolean("quality_gate_v090",quality.isChecked()).putBoolean("memory_guard_v090",memory.isChecked()).putBoolean("thermal_adaptive_v090",thermal.isChecked()).apply();watchdog.setOnClickListener(save);quality.setOnClickListener(save);memory.setOnClickListener(save);thermal.setOnClickListener(save);V090RuntimeGuard.Snapshot snap=V090RuntimeGuard.check(this);guards.addView(note("Free RAM ~"+snap.freeMb+" MB • thermal status "+snap.thermal));c.addView(guards);

        LinearLayout queue=box("Room Queue + Watchdog");queue.addView(label(controller.queueSummary(),13,true));Button retry=button("Retry Failed / Stalled");retry.setOnClickListener(v->{controller.queue.retryFailed();V090WorkController.startExport(this);showStability();});queue.addView(retry);Button pause=button("Pause pending queue");pause.setOnClickListener(v->{controller.queue.pausePending();showStability();});queue.addView(pause);Button resume=button("Resume queue");resume.setOnClickListener(v->{controller.queue.resumePaused();V090WorkController.startExport(this);showStability();});queue.addView(resume);c.addView(queue);

        LinearLayout safe=box("Safe Mode + Recovery");Switch sm=new Switch(this);sm.setText("Safe Mode");sm.setTextColor(fg());sm.setChecked(prefs90().getBoolean("safe_mode_v090",false));sm.setOnCheckedChangeListener((b,on)->{controller.setSafeMode(on);applyFollowRuntime();showStability();});safe.addView(sm);safe.addView(note("Two crashes in a short window automatically enable Safe Mode: fixed camera, AVC, Quick scan, minimal tracking."));String key=projectKey();safe.addView(note("Latest actor-index backup: "+V090RecoveryManager.latest(this,key)));Button backup=button("Backup actor index now");backup.setOnClickListener(v->Toast.makeText(this,V090RecoveryManager.backupIndex(this,key,"manual")?"Backup saved":"No index to back up",Toast.LENGTH_SHORT).show());safe.addView(backup);Button restore=button("Restore latest actor index");restore.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("Restore actor index?").setMessage("The current actor index will be replaced by the newest recovery snapshot.").setNegativeButton("Cancel",null).setPositiveButton("Restore",(d,w)->{if(V090RecoveryManager.restoreLatest(this,key)){setScan(null);Toast.makeText(this,"Restored",Toast.LENGTH_SHORT).show();showGalleryV2();}else Toast.makeText(this,"No backup",Toast.LENGTH_SHORT).show();}).show());safe.addView(restore);c.addView(safe);

        LinearLayout model=box("Face Model Auto Benchmark");model.addView(note("Current: "+prefs90().getInt("face_threads_v090",0)+" thread(s) • "+String.format(Locale.US,"%.1f ms/embedding",prefs90().getFloat("face_benchmark_ms_v090",0))));Button bench=button("Re-run Face Model Benchmark");bench.setOnClickListener(v->{Toast.makeText(this,"Benchmark running…",Toast.LENGTH_SHORT).show();worker90.execute(()->{V090FaceBenchmark.Result r=V090FaceBenchmark.run(this);runOnUiThread(()->{Toast.makeText(this,String.format(Locale.US,"Best: %d thread(s) • %.1f ms",r.threads,r.ms),Toast.LENGTH_LONG).show();showStability();});});});model.addView(bench);c.addView(model);
        c.addView(note("Architecture v0.9: centralized controller + unified work controller + Room queue + RecyclerView Gallery V2. Legacy screens remain available for compatibility, but the new reliability path avoids their fragile queue/gallery state."));}

    private CheckBox check(String s,boolean v){CheckBox c=new CheckBox(this);c.setText(s);c.setChecked(v);c.setTextColor(fg());return c;}private interface IntChange{void set(int v);}private void addSeek(LinearLayout box,String name,int min,int max,int saved,IntChange cb){TextView l=note(name+": "+saved+"%");box.addView(l);SeekBar b=new SeekBar(this);b.setMax(max-min);b.setProgress(Math.max(0,Math.min(max-min,saved-min)));b.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar s,int p,boolean from){int v=p+min;l.setText(name+": "+v+"%");cb.set(v);}public void onStartTrackingTouch(SeekBar s){}public void onStopTrackingTouch(SeekBar s){}});box.addView(b);}

    private void applyFollowRuntime(){SharedPreferences p=prefs90();boolean follow=controller!=null?controller.faceFollow():p.getBoolean("v090_face_follow_enabled",false);TrackingPanEffect.configure(follow&&p.getBoolean("dynamic_zoom_v050",false),p.getBoolean("lost_recovery_v050",true),p.getBoolean("identity_lock_v050",true),p.getFloat("max_zoom_v050",1.14f));try{TrackingPanEffect.configureMotion(follow?p.getString("tracking_motion_v061","Slow"):"Fixed actor average",p.getInt("tracking_follow_v061",18)/100f,p.getInt("tracking_deadzone_v061",16)/100f,p.getInt("tracking_fixed_x_v061",50)/100f,p.getInt("tracking_fixed_y_v061",42)/100f);}catch(Throwable ignored){}try{TrackingPanEffect.configureV090(p.getBoolean("cinematic_follow_v090",false)&&follow,p.getInt("cinematic_speed_v090",10)/100f,p.getInt("cinematic_deadzone_v090",16)/100f,p.getBoolean("manual_path_v090",false)?p.getString("tracking_path_v090",""):"",p.getInt("tracking_freeze_v090",100)/100f);}catch(Throwable ignored){}}

    private void renderPreview(){ActorScanStore.Cluster a=selectedActor();ArrayList<Uri> vs=videos();if(a==null||vs.isEmpty()){Toast.makeText(this,"Scan and select an actor first",Toast.LENGTH_SHORT).show();return;}int vi=0;outer:for(ActorScanStore.Hit h:a.hits)if(h.videoIndex>=0&&h.videoIndex<vs.size()){vi=h.videoIndex;break outer;}Toast.makeText(this,"Rendering temporary 4-second preview…",Toast.LENGTH_LONG).show();final int videoIndex=vi;V090PreviewRenderer.render(this,vs.get(videoIndex),videoIndex,a,(file,error)->{if(error!=null){Toast.makeText(this,"Preview failed: "+error,Toast.LENGTH_LONG).show();return;}VideoView vv=new VideoView(this);vv.setVideoPath(file.getAbsolutePath());AlertDialog d=new AlertDialog.Builder(this).setTitle("4s Smart Crop Preview").setView(vv).setNegativeButton("Close",null).create();d.setOnShowListener(x->{vv.setOnPreparedListener(mp->{mp.setLooping(true);vv.start();});});d.setOnDismissListener(x->{try{vv.stopPlayback();}catch(Throwable ignored){}file.delete();});d.show();});}

    private void showDiagnostics(){setPage("diagnostics_v090");LinearLayout c=content();if(c==null)return;c.removeAllViews();c.addView(label("Diagnostics Center • v0.9",21,true));c.addView(label(controller.queueSummary(),13,true));c.addView(note("Work: "+prefs90().getString("v090_work_kind","idle")+" • "+prefs90().getString("v090_work_status","Ready")+" • "+prefs90().getInt("v090_work_progress",0)+"%"));c.addView(note("Safe mode: "+prefs90().getBoolean("safe_mode_v090",false)+" • crash burst: "+prefs90().getInt("v090_crash_burst",0)));LinearLayout actions=new LinearLayout(this);actions.setOrientation(LinearLayout.HORIZONTAL);Button test=button("Run Self Test");test.setOnClickListener(v->{Toast.makeText(this,"Self-test running…",Toast.LENGTH_SHORT).show();worker90.execute(()->{String r=V090SelfTest.run(this);runOnUiThread(()->new AlertDialog.Builder(this).setTitle("Integrity Self-Test").setMessage(r).setPositiveButton("OK",null).show());});});actions.addView(test,new LinearLayout.LayoutParams(0,-2,1));Button copy=button("Copy Diagnostics");copy.setOnClickListener(v->{String txt=V090Diagnostics.readLast(this)+"\n"+V090Diagnostics.readEvents(this)+"\n"+controller.queueSummary();((android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("Actor Sticker Diagnostics",txt));Toast.makeText(this,"Copied",Toast.LENGTH_SHORT).show();});actions.addView(copy,new LinearLayout.LayoutParams(0,-2,1));c.addView(actions);Button reset=button("Reset only broken queue jobs");reset.setOnClickListener(v->{controller.queue.clearBroken();showDiagnostics();});c.addView(reset);c.addView(label("Last error / crash",15,true));TextView err=note(V090Diagnostics.readLast(this));err.setTextIsSelectable(true);c.addView(err);c.addView(label("Recent diagnostic events",15,true));TextView ev=note(V090Diagnostics.readEvents(this));ev.setTextIsSelectable(true);c.addView(ev);}

    @SuppressWarnings("unchecked") private ArrayList<Uri> videos(){try{Field f=MainActivity.class.getDeclaredField("videos");f.setAccessible(true);return new ArrayList<>((ArrayList<Uri>)f.get(this));}catch(Throwable e){return new ArrayList<>();}}private LinearLayout content(){try{Field f=MainActivity.class.getDeclaredField("content");f.setAccessible(true);return(LinearLayout)f.get(this);}catch(Throwable e){return null;}}private ActorScanStore.ScanState scan(){try{Field f=MainActivity.class.getDeclaredField("scanState");f.setAccessible(true);return(ActorScanStore.ScanState)f.get(this);}catch(Throwable e){return null;}}private void setScan(ActorScanStore.ScanState s){try{Field f=MainActivity.class.getDeclaredField("scanState");f.setAccessible(true);f.set(this,s);}catch(Throwable ignored){}}private int selectedId(){try{Field f=MainActivity.class.getDeclaredField("selectedClusterId");f.setAccessible(true);return f.getInt(this);}catch(Throwable e){return-1;}}private void setSelectedId(int id){try{Field f=MainActivity.class.getDeclaredField("selectedClusterId");f.setAccessible(true);f.setInt(this,id);}catch(Throwable ignored){}}private ActorScanStore.Cluster selectedActor(){ActorScanStore.ScanState s=scan();return s==null?null:s.byId(selectedId());}private void setPage(String s){try{Field f=MainActivity.class.getDeclaredField("currentPage");f.setAccessible(true);f.set(this,s);}catch(Throwable ignored){}}private String page(){try{Field f=MainActivity.class.getDeclaredField("currentPage");f.setAccessible(true);return String.valueOf(f.get(this));}catch(Throwable e){return"";}}private String projectKey(){try{Field f=MainActivity.class.getDeclaredField("currentProjectKey");f.setAccessible(true);String s=(String)f.get(this);if(s!=null&&!s.isEmpty())return s;}catch(Throwable ignored){}try{Method m=MainActivity.class.getDeclaredMethod("computeProjectKey");m.setAccessible(true);return(String)m.invoke(this);}catch(Throwable e){return"";}}
    private void invokeBase(String name,Class<?>[] types,Object[] args){Class<?> q=getClass().getSuperclass();while(q!=null){try{Method m=q.getDeclaredMethod(name,types);m.setAccessible(true);m.invoke(this,args);return;}catch(NoSuchMethodException e){q=q.getSuperclass();}catch(Throwable e){V090Diagnostics.log(this,"invoke:"+name,e);return;}}}
}
